/**
 * Types for Page Context received from GEA Portal
 */

// ============================================================================
// Modal Context
// ============================================================================

export interface ModalContext {
  /** Modal type identifier */
  type: string;
  /** Modal title */
  title?: string;
  /** Type of entity in modal */
  entityType?: string;
  /** Entity ID */
  entityId?: string | number;
  /** Entity display name */
  entityName?: string;
  /** Additional modal data */
  data?: Record<string, any>;
}

// ============================================================================
// Edit Context
// ============================================================================

export interface EditContext {
  /** Whether editing is active */
  isEditing: boolean;
  /** Type of entity being edited */
  entityType: string;
  /** Entity ID */
  entityId: string | number;
  /** Entity display name */
  entityName?: string;
  /** Fields available for editing */
  fields?: string[];
  /** Original data before editing */
  originalData?: Record<string, any>;
  /** Current edited data */
  currentData?: Record<string, any>;
}

// ============================================================================
// Tab Context
// ============================================================================

export interface TabContext {
  /** Tab group identifier */
  tabGroup: string;
  /** Currently active tab */
  activeTab: string;
  /** All available tabs */
  availableTabs: string[];
}

// ============================================================================
// Form Context
// ============================================================================

export interface FormContext {
  /** Form identifier */
  formName: string;
  /** Current step (1-indexed) */
  currentStep?: number;
  /** Total steps */
  totalSteps?: number;
  /** Completed field names */
  completedFields?: string[];
  /** Pending field names */
  pendingFields?: string[];
  /** Validation errors */
  validationErrors?: string[];
}

// ============================================================================
// Full Page Context
// ============================================================================

export interface PageContext {
  // Route
  route: string;
  pageTitle?: string;
  pageDescription?: string;

  // UI State
  modal?: ModalContext | null;
  edit?: EditContext | null;
  tab?: TabContext | null;
  form?: FormContext | null;

  // Custom data
  custom?: Record<string, any>;

  // Metadata
  timestamp: number;
  changeType: 'navigation' | 'modal' | 'edit' | 'tab' | 'form' | 'custom';
}

// ============================================================================
// Message Types
// ============================================================================

export interface ContextUpdateMessage {
  type: 'CONTEXT_UPDATE';
  context: PageContext;
}

// ============================================================================
// API Types (for static page info from GEA Portal)
// ============================================================================

export interface PageContextApiResponse {
  route: string;
  title: string;
  purpose: string;
  audience: 'public' | 'staff' | 'admin';
  steps?: string[];
  tips?: string[];
  features?: string[];
  autoGenerated: boolean;
  lastUpdated: string;
}
