/**
 * Shared TypeScript Types for GEA AI Assistant
 */

// ============================================================================
// Page Context Types
// ============================================================================

export interface PageContext {
  route: string;
  title: string;
  purpose: string;
  audience: 'public' | 'staff' | 'admin';
  steps?: string[];
  tips?: string[];
  features?: string[];
  autoGenerated: boolean;
  lastUpdated: string;
}

// ============================================================================
// Function Call Types
// ============================================================================

export interface FunctionCallResult {
  success: boolean;
  data?: any;
  error?: string;
}

// ============================================================================
// API Request/Response Types
// ============================================================================

export interface ChatRequest {
  message: string;
  threadId?: string | null;
  sourceUrl?: string | null;
}

export interface ChatResponse {
  reply: string;
  threadId: string;
  status: 'success' | 'error';
  error?: string;
}

// ============================================================================
// OpenAI Function Definition Types
// ============================================================================

export interface FunctionDefinition {
  name: string;
  description: string;
  parameters: {
    type: string;
    properties: Record<string, {
      type: string;
      description: string;
      enum?: string[];
    }>;
    required: string[];
  };
}

export interface OpenAITool {
  type: 'function';
  function: FunctionDefinition;
}
